server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
      routes:
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/auth-server/**
          filters:
            - RewritePath=/api/auth-server/(?<path>.*), /$\{path}
        - id: storage-server
          uri: lb://STORAGE-SERVER
          predicates:
            - Path=/api/storage-server/**
          filters:
            - RewritePath=/api/storage-server/(?<path>.*), /$\{path}
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"