server:
  port: 8054
spring:
  servlet:
    multipart:
      max-file-size: 2500MB
      max-request-size: 2500MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:3308/cloud-storage-db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
minio:
  endpoint: http://localhost:9000
  accessKey: ROOTUSER
  secretKey: ROOTUSER